name: cardapio
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  hive: 2.2.2
  hive_flutter: 1.1.0
  hive_generator: 1.1.3
  cached_network_image: 3.2.1
  intl: 0.17.0
  badges: 2.0.3
  flutter_spinbox: 0.9.0
  uuid: 3.0.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

